In [1]:
# Input the DB to Memory
import pandas as pd
import numpy as np
print("Loading DB...")
dfs = pd.read_csv("terrorism_red_cat.csv")
print("DB Read...")
#print(data_file.sheet_names)
#dfs = data_file.parse(data_file.sheet_names[0])
#print("DB Parsed...")
del(dfs['Unnamed: 0'])

Loading DB...
DB Read...


In [2]:
dimensions = ['nperps', 'nkill', 'nwound',]

columns = dfs.columns

for cols in columns:
    if cols == 'gname':
        continue
    if cols not in dimensions:
        del(dfs[cols])

columns = dfs.columns
print(columns)
print(dimensions)

Index(['gname', 'nperps', 'nkill', 'nwound'], dtype='object')
['nperps', 'nkill', 'nwound']


In [3]:
print("Loading DB...")
dfs_names = pd.read_csv("final_names.csv")
print("DB Read...")
#print(data_file.sheet_names)
#dfs = data_file.parse(data_file.sheet_names[0])
#print("DB Parsed...")
print(type(dfs_names['group']))

Loading DB...
DB Read...
<class 'pandas.core.series.Series'>


In [4]:
import collections
group_dict = collections.OrderedDict()
for name in dfs_names['group']:
    group_dict[(name,-1)] = []
    for index in range(len(dimensions)):
        group_dict[(name,-1)].append(0)
print(group_dict)

OrderedDict([(('Bougainville Revolutionary Army (BRA)', -1), [0, 0, 0]), (('Kanak Socialist National Liberation Front', -1), [0, 0, 0]), (('September 11 Commandos', -1), [0, 0, 0]), (('Kanak Separatists', -1), [0, 0, 0]), (('Animal Liberation Front (ALF)', -1), [0, 0, 0]), (('Anti-Government Rebels', -1), [0, 0, 0]), (('Croatian Nationalists', -1), [0, 0, 0]), (('Free Papua Movement (OPM-Organisasi Papua Merdeka)', -1), [0, 0, 0]), (('Informal Anarchist Federation', -1), [0, 0, 0]), (('National Committee Against Independence (CNCI)', -1), [0, 0, 0]), (('Vanuatu Mobile Force (VMF)', -1), [0, 0, 0]), (('Combat 18', -1), [0, 0, 0]), (('Greek Bulgarian Armenian Front', -1), [0, 0, 0]), (('Guadalcanal Liberation Army', -1), [0, 0, 0]), (('Isatabu Freedom Movement (IFM)', -1), [0, 0, 0]), (('Lufa Tribesmen', -1), [0, 0, 0]), (('Pacific Popular Front', -1), [0, 0, 0]), (('Palestine Liberation Organization (PLO)', -1), [0, 0, 0]), (('Paupa New Guinea Troops', -1), [0, 0, 0]), (('Zapatista Nati

In [5]:
for index, gname in enumerate(dfs['gname']):
    for i in range(len(dimensions)):
        #if dimensions[i] == 'nkill':
        #   print(str(dfs[dimensions[i]][index]))
        if str(dfs[dimensions[i]][index]) == 'nan' or dfs[dimensions[i]][index] < 0 :
            continue
        group_dict[(gname,-1)][i] += dfs[dimensions[i]][index] 

In [6]:
def get_index(groups, name):
    for i in range(len(groups)):
        if groups[i] == name:
            return i
    return -1

unique_groups, group_counts = np.unique(dfs['gname'], return_counts=True)
for gname, c_id in group_dict:
    index = get_index(unique_groups,gname)
    if index == -1:
        print("WTF. " + gname)
    nevents = group_counts[index]
    #print(nevents)
    #nevents = nevents[0]
    for i in range(len(group_dict[(gname,c_id)])):
        group_dict[(gname,c_id)][i] = group_dict[(gname,c_id)][i]/nevents
    #group_dict[(gname,c_id)].append(nevents)

print(group_dict)
print(type(nevents))
print(nevents)

OrderedDict([(('Bougainville Revolutionary Army (BRA)', -1), [0.95238095238095233, 0.95238095238095233, 1.4285714285714286]), (('Kanak Socialist National Liberation Front', -1), [3.0, 0.80000000000000004, 1.2]), (('September 11 Commandos', -1), [0.0, 2.0, 0.0]), (('Kanak Separatists', -1), [0.0, 4.5, 1.0]), (('Animal Liberation Front (ALF)', -1), [0.47787610619469029, 0.0, 0.035398230088495575]), (('Anti-Government Rebels', -1), [1.1428571428571428, 1.5714285714285714, 0.5714285714285714]), (('Croatian Nationalists', -1), [0.6470588235294118, 1.2647058823529411, 3.0]), (('Free Papua Movement (OPM-Organisasi Papua Merdeka)', -1), [6.9655172413793105, 1.4827586206896552, 0.7931034482758621]), (('Informal Anarchist Federation', -1), [0.12820512820512819, 0.0, 0.20512820512820512]), (('National Committee Against Independence (CNCI)', -1), [0.0, 0.0, 0.0]), (('Vanuatu Mobile Force (VMF)', -1), [69.0, 0.0, 0.0]), (('Combat 18', -1), [0.0, 0.0, 3.5]), (('Greek Bulgarian Armenian Front', -1), 

In [7]:
print(unique_groups)
print(group_counts)

['14 K Triad' '20 December Movement (M-20)'
 '23rd of September Communist League' "31 January People's Front (FP-31)"
 'Abdullah Azzam Brigades' 'Abu Hafs al-Masri Brigades'
 'Abu Nidal Organization (ANO)' 'Abu Sayyaf Group (ASG)' 'Action Directe'
 'African National Congress (South Africa)' 'Al-Aqsa Martyrs Brigade'
 'Al-Fatah' "Al-Gama'at al-Islamiyya (IG)" 'Al-Ittihaad al-Islami (AIAI)'
 'Al-Khobar' 'Al-Nusrah Front' 'Al-Qaida' 'Al-Qaida in Iraq'
 'Al-Qaida in the Arabian Peninsula (AQAP)'
 'Al-Qaida in the Islamic Maghreb (AQIM)' 'Al-Shabaab'
 'Albanian National Army (ANA)' 'Alex Boncayao Brigade (ABB)' 'Alfaro Vive'
 'Algeisk Wolves' 'Algerian Islamic Extremists'
 "All Burma Students' Democratic Front (ABSDF)"
 'Allied Democratic Forces (ADF)' 'America Battalion' 'Angry Brigade'
 'Animal Liberation Front (ALF)' 'Ansar Allah' 'Ansar al-Din Front'
 'Anti-Government Rebels' 'Anti-Imperialist Students Council'
 'Anti-Narita Extremists' 'April 6th Liberation Movement'
 'Armed Commandos 

In [8]:
dimension_arr = None # This should be a NumPy array 
for key_tup in group_dict:
    if dimension_arr == None:
        dimension_arr = np.asarray(group_dict[key_tup]) # First iteration, create the array
    else:
        dimension_arr = np.vstack((dimension_arr, group_dict[key_tup]))

print(dimension_arr)
from sklearn import preprocessing
dim_arr_scaled = preprocessing.scale(dimension_arr)
print(dim_arr_scaled)

[[ 0.95238095  0.95238095  1.42857143]
 [ 3.          0.8         1.2       ]
 [ 0.          2.          0.        ]
 ..., 
 [ 0.          1.          0.11111111]
 [ 3.6         0.          0.4       ]
 [ 0.          0.          0.        ]]


D:\Users\Avradip\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  app.launch_new_instance()


[[-0.28597074 -0.23965638 -0.13100057]
 [-0.11133869 -0.25049511 -0.13598272]
 [-0.36719494 -0.16514014 -0.162139  ]
 ..., 
 [-0.36719494 -0.23626928 -0.15971712]
 [-0.06016744 -0.30739843 -0.15342024]
 [-0.36719494 -0.30739843 -0.162139  ]]


In [9]:
from sklearn.cluster import KMeans
import numpy as np
k=5
kmeans = KMeans(n_clusters=k,random_state=0).fit(dimension_arr)

print(len(group_dict))
print(len(group_dict.keys()))
print(len(kmeans.labels_))
#rint(group_dict.keys())
#rint(kmeans.labels_)
#i = 0
#for key_tup in group_dict:
#    group_dict[(key_tup[0],kmeans.labels_[i])] = group_dict.pop(key_tup) 
#    i += 1

#rint(group_dict)

403
403
403


In [10]:

print(len(group_dict))
print(len(kmeans.labels_))
print(dim_arr_scaled.shape)

result_dict = {}
for i in range(k):
    result_dict[i] = []

i = 0
for key_tup in group_dict:
    if i == 403:
        print("Wtf!" + str(group_dict[key_tup]))
        break
    #print(key_tup)
    #print(i)
    #print(group_dict[key_tup])
    #print(kmeans.labels_[i])
    result_dict[kmeans.labels_[i]].append(key_tup[0]) 
    i += 1
    

403
403
(403, 3)


In [11]:
print(result_dict)

{0: ['Bougainville Revolutionary Army (BRA)', 'Kanak Socialist National Liberation Front', 'September 11 Commandos', 'Kanak Separatists', 'Animal Liberation Front (ALF)', 'Anti-Government Rebels', 'Croatian Nationalists', 'Free Papua Movement (OPM-Organisasi Papua Merdeka)', 'Informal Anarchist Federation', 'National Committee Against Independence (CNCI)', 'Combat 18', 'Greek Bulgarian Armenian Front', 'Guadalcanal Liberation Army', 'Isatabu Freedom Movement (IFM)', 'Lufa Tribesmen', 'Pacific Popular Front', 'Palestine Liberation Organization (PLO)', 'Paupa New Guinea Troops', 'Zapatista National Liberation Army', 'Farabundo Marti National Liberation Front (FMLN)', 'Nicaraguan Democratic Force (FDN)', 'Sandinista National Liberation Front (FSLN)', "People's Liberation Forces (FPL)", 'Guerrilla Army of the Poor (EGP)', 'Nicaraguan Resistance', 'Guatemalan National Revolutionary Unity (URNG)', 'Death Squad', 'Revolutionary Organization of People in Arms (ORPA)', "People's Revolutionary A

In [12]:
print(kmeans.cluster_centers_)

[[  2.10642186e+00   2.64126488e+00   3.66706305e+00]
 [  8.57142857e-01   3.00000000e+00   8.57571429e+02]
 [  1.14084848e+00   3.32453333e+01   1.40319636e+02]
 [  1.03333333e+01   1.24750000e+02   0.00000000e+00]
 [  5.26588500e+01   4.72356554e+00   3.51654732e+00]]


In [13]:
print(dimensions)

['nperps', 'nkill', 'nwound']
